version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.8"

sphinx:
  configuration: conf.py

python:
  install:
    - requirements: requirements.txt
    - requirements: theme.txt

submodules:
  include: all
  recursive: true
